pipeline {
    agent any

    tools {
        maven 'Maven'
        jdk 'JDK21'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Testes Unitários') {
            steps {
                dir('brute-api') {
                    echo 'Rodando testes do Spring Boot...'

                    sh 'chmod +x mvnw'
                    sh './mvnw clean test'
                }
            }
        }
    }

    post {
        always {
            junit 'brute-api/target/surefire-reports/*.xml'
        }
        success {
            echo 'Todos os testes passaram com sucesso! 🎉'
        }
        failure {
            echo 'Ops! Alguns testes falharam. Verifique os relatórios. 🚨'
        }
    }
}